@baseurl =https://localhost:7017


/// register
POST   {{baseurl}}/api/v1/auth/register
Content-Type: application/json

{
    "FirstName": "das",
    "LastName": "Doe",
    "Email": "mahmoudexample@example.com",
    "Password": "P@ssword1"
}
###################


POST   {{baseurl}}/api/v1/auth/login
Content-Type: application/json

{
    "Email": "mahmoud@example.com",
    "Password": "P@ssword1"
}

###################

GET    {{baseurl}}/api/v1/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NWM0MjhkNS1mZGRiLTRjZDUtOWFmYS1mNmM0ZmRhNWE1YmMiLCJlbWFpbCI6Im1haG1vdWRAZXhhbXBsZS5jb20iLCJyb2xlIjoiVXNlciIsIm5iZiI6MTc1OTE2MjI0MiwiZXhwIjoxNzU5MTY1ODQyLCJpYXQiOjE3NTkxNjIyNDIsImlzcyI6ImxvY2FsaG9zdCIsImF1ZCI6ImxvY2FsaG9zdCJ9.p54h03I52ZF4MzvLAxRWd4Bz_CgUjwAVTk4M7gJg4x

